trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ANT_HOME: '/usr/share/ant'
  JAVA_HOME: '/usr/lib/jvm/java-11-openjdk-amd64'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Ant@1
    inputs:
      buildFile: 'build.xml'
      targets: 'compile'
      publishJUnitResults: false
