name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Download GlassFish
        run: |
          wget https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.24.zip
          unzip glassfish-7.0.24.zip -d $HOME
          echo "GlassFish installed at $HOME/glassfish7"

      - name: Download NetBeans CopyLibs
        run: |
          mkdir -p lib
          wget -O lib/org-netbeans-modules-java-j2seproject-copylibstask.jar https://hub.spigotmc.org/stash/projects/PLUGIN/repos/essentials/raw/lib/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar?at=88c1b785af81cfe213fb771243f1605d394619ab

      - name: Download MySQL Connector
        run: |
          wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.3.0.zip
          unzip mysql-connector-j-9.3.0.zip
          mkdir -p build/web/WEB-INF/lib
          mkdir -p web/WEB-INF/lib
          # extra create parh
          mkdir -p build/classes
          cp mysql-connector-j-9.3.0/mysql-connector-j-9.3.0.jar build/web/WEB-INF/lib/mysql-connector-j-9.2.0.jar
          cp mysql-connector-j-9.3.0/mysql-connector-j-9.3.0.jar web/WEB-INF/lib/mysql-connector-j-9.2.0.jar
          mkdir -p lib/MYSQL
          cp mysql-connector-j-9.3.0/mysql-connector-j-9.3.0.jar lib/MYSQL/mysql-connector-j-9.2.0.jar
          
      - name: Download Jakarta EE dependencies
        run: |
          mkdir -p lib/jakartaee
          
          wget -O lib/jakartaee/jakarta.jakartaee-api-9.1.0.jar https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-api/9.1.0/jakarta.jakartaee-api-9.1.0.jar
          wget -O lib/jakartaee/jakarta.servlet-api-5.0.0.jar https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar
          
          mkdir -p build/web/WEB-INF/lib/
          cp lib/jakartaee/*.jar build/web/WEB-INF/lib/
          
      - name: Build WAR with Ant
        run: ant war -Dj2ee.server.home=$HOME/glassfish7 -Dlibs.CopyLibs.classpath=lib/org-netbeans-modules-java-j2seproject-copylibstask.jar -Dlibs.MYSQL.classpath=lib/MYSQL/mysql-connector-j-9.2.0.jar -Dj2ee.platform.classpath=lib/jakartaee/jakarta.jakartaee-api-9.1.0.jar:lib/jakartaee/jakarta.servlet-api-5.0.0.jar

      - name: Prepare WAR for Docker
        run: |
          mkdir -p dist
          cp dist/app.war dist/mpnotes_java.war

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker_img

      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
