name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Build WAR with Ant
      run: ant war

    - name: Prepare WAR for Docker
      run: |
        mkdir -p dist
        cp dist/app.war dist/mpnotes_java.war

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dock_img_:$(date +%s)
