name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  get-glassfish:
    runs-on: ubuntu-latest
    steps:
      - name: Download GlassFish
        run: |
          wget https://download.eclipse.org/ee4j/glassfish/glassfish-6.2.5.zip
          unzip glassfish-6.2.5.zip -d $HOME
          echo "GlassFish installed at $HOME/glassfish6"
      - name: Show GlassFish version
        run: $HOME/glassfish6/bin/asadmin version

  build:
    runs-on: ubuntu-latest
    needs: get-glassfish
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Download GlassFish
        run: |
          wget https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.24.zip
          unzip glassfish-7.0.24.zip -d $HOME
          echo "GlassFish installed at $HOME/glassfish7"

      - name: Build WAR with Ant
        run: ant war -Dj2ee.server.home=$HOME/glassfish7

      - name: Prepare WAR for Docker
        run: |
          mkdir -p dist
          cp dist/app.war dist/mpnotes_java.war

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dock_img_:$(date +%s)
