name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Download GlassFish
        run: |
          wget https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.24.zip
          unzip glassfish-7.0.24.zip -d $HOME
          echo "GlassFish installed at $HOME/glassfish7"

      - name: Download NetBeans CopyLibs
        run: |
          mkdir -p lib
          wget -O lib/org-netbeans-modules-java-j2seproject-copylibstask.jar https://repo1.maven.org/maven2/org/netbeans/modules/org-netbeans-modules-java-j2seproject-copylibstask/RELEASE170/org-netbeans-modules-java-j2seproject-copylibstask-RELEASE170.jar

      - name: Build WAR with Ant
        run: ant war -Dj2ee.server.home=$HOME/glassfish7 -Dlibs.CopyLibs.classpath=lib/org-netbeans-modules-java-j2seproject-copylibstask.jar

      - name: Prepare WAR for Docker
        run: |
          mkdir -p dist
          cp dist/app.war dist/mpnotes_java.war

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dock_img_:$(date +%s)
